#!/usr/bin/env bash
set -euo pipefail

run_id="${AGENT_GEST_GITBUTLER_GITHUB_RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)-$$}"
lab_root="${AGENT_GEST_GITBUTLER_GITHUB_LAB:-/tmp/agent-gest-gitbutler-live-github-lab-$run_id}"
owner="${AGENT_GEST_GITBUTLER_GITHUB_OWNER:-}"
visibility="${AGENT_GEST_GITBUTLER_GITHUB_VISIBILITY:-private}"
repo_prefix="${AGENT_GEST_GITBUTLER_GITHUB_REPO_PREFIX:-agent-gest-gitbutler-live}"
keep_repos="${AGENT_GEST_GITBUTLER_KEEP_GITHUB_REPOS:-0}"
logs_dir="$lab_root/logs"
tutorial="$lab_root/gitbutler-live-github-workflow-tutorial.md"

created_repos=()
created_dirs=()
made_full_repo=""
made_dir=""

usage() {
  cat <<'USAGE'
Usage: scripts/run_gitbutler_github_integration_lab.sh

Runs the four GitButler parity examples against four separate temporary GitHub repos:

1. Plain GitButler branch PR flow
2. Multi-commit GitButler branch PR flow
3. Stacked GitButler PR flow
4. Parallel physical git worktree PR flow

The script requires authenticated GitHub CLI access and the delete_repo scope
because it destroys the temporary repos with `gh repo delete --yes`.

Optional environment:
  AGENT_GEST_GITBUTLER_GITHUB_OWNER=<owner>        GitHub user/org for temp repos
  AGENT_GEST_GITBUTLER_GITHUB_VISIBILITY=private  private|public, default private
  AGENT_GEST_GITBUTLER_GITHUB_LAB=/tmp/path       output/log directory
  AGENT_GEST_GITBUTLER_KEEP_GITHUB_REPOS=1        keep repos for debugging
USAGE
}

die() {
  echo "error: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

cleanup() {
  status=$?
  set +u
  if [ "$keep_repos" = "1" ]; then
    echo "Keeping GitHub repos because AGENT_GEST_GITBUTLER_KEEP_GITHUB_REPOS=1:" >&2
    if [ "${#created_repos[@]}" -gt 0 ]; then
      printf '  %s\n' "${created_repos[@]}" >&2
    fi
    exit "$status"
  fi

  [ -d "$logs_dir" ] || mkdir -p "$logs_dir"
  for full_repo in "${created_repos[@]}"; do
    echo "Deleting temporary GitHub repo: $full_repo" >&2
    gh repo delete "$full_repo" --yes >>"$logs_dir/cleanup.log" 2>&1 || {
      echo "warning: failed to delete $full_repo; see $logs_dir/cleanup.log" >&2
    }
  done

  for dir in "${created_dirs[@]}"; do
    rm -rf "$dir"
  done

  exit "$status"
}

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
esac

trap cleanup EXIT

case "$visibility" in
  private|public) ;;
  *) die "AGENT_GEST_GITBUTLER_GITHUB_VISIBILITY must be private or public" ;;
esac

mkdir -p "$logs_dir"

require_command git
require_command gh
require_command but

auth_status="$(gh auth status -h github.com 2>&1)" || {
  printf '%s\n' "$auth_status" >&2
  die "gh is not authenticated; run gh auth login"
}

printf '%s\n' "$auth_status" >"$logs_dir/gh-auth-status.log"
if ! printf '%s\n' "$auth_status" | grep -q "delete_repo"; then
  die "gh is authenticated but lacks delete_repo scope; run: gh auth refresh -h github.com -s delete_repo"
fi

if [ -z "$owner" ]; then
  owner="$(gh api user -q .login)"
fi

cat >"$tutorial" <<EOF
# Live GitHub GitButler Workflow Lab

Run ID: \`$run_id\`

Owner: \`$owner\`

This tutorial trace was generated by running each GitButler parity example
against a separate temporary GitHub repository. The repositories are deleted at
the end of the run with \`gh repo delete --yes\`.

EOF

append_tutorial() {
  cat >>"$tutorial"
}

log_cmd() {
  printf '\n$'
  printf ' %q' "$@"
  printf '\n'
  "$@"
}

write_file() {
  local path="$1"
  shift
  printf '%s\n' "$@" >"$path"
  printf '\n$ printf ... > %q\n' "$path"
}

make_repo() {
  local slug="$1"
  local repo_name="$repo_prefix-$run_id-$slug"
  local full_repo="$owner/$repo_name"
  local dir="$lab_root/$slug"

  mkdir -p "$dir"
  created_dirs+=("$dir")
  created_repos+=("$full_repo")

  (
    cd "$dir"
    log_cmd git init -b main
    log_cmd git config user.name "workflow-test"
    log_cmd git config user.email "workflow-test@example.invalid"
    log_cmd gh repo create "$full_repo" "--$visibility" --source=. --remote=origin --disable-issues --disable-wiki
  )

  made_full_repo="$full_repo"
  made_dir="$dir"
}

init_main() {
  write_file README.md "# $1"
  mkdir -p src
  write_file src/app.txt "base"
  log_cmd git add README.md src/app.txt
  log_cmd git commit -m "chore: initialize $1"
  log_cmd git push -u origin main
  log_cmd but setup
}

create_pr() {
  local full_repo="$1"
  local branch="$2"
  local base="$3"
  local title="$4"
  local body="$5"

  if but pr new "$branch" -m "$title"$'\n\n'"$body" --json; then
    return 0
  fi

  echo "but pr new failed; falling back to gh pr create" >&2
  gh pr create --repo "$full_repo" --base "$base" --head "$branch" --title "$title" --body "$body"
}

verify_pr_count() {
  local full_repo="$1"
  local expected="$2"
  local count
  count="$(gh pr list --repo "$full_repo" --state open --json number --jq 'length')"
  [ "$count" -eq "$expected" ] || die "expected $expected open PRs, got $count"
}

verify_pr_base() {
  local full_repo="$1"
  local branch="$2"
  local expected_base="$3"
  local actual_base
  actual_base="$(gh pr view "$branch" --repo "$full_repo" --json baseRefName --jq .baseRefName)"
  [ "$actual_base" = "$expected_base" ] ||
    die "expected PR for $branch to target $expected_base, got $actual_base"
}

run_flow() {
  local slug="$1"
  local title="$2"
  local func="$3"
  local log="$logs_dir/$slug.log"

  echo "Running $title"
  append_tutorial <<EOF
## $title

Full command log: \`$log\`

EOF

  {
    echo "# $title"
    "$func"
  } >"$log" 2>&1

  append_tutorial <<EOF
\`\`\`text
$(tail -n 80 "$log")
\`\`\`

EOF
}

flow_plain_branch() {
  local full_repo dir
  make_repo "plain-branch"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "plain GitButler branch"

  log_cmd but branch new demo/plain-branch
  write_file plain.txt "plain branch change"
  log_cmd but commit demo/plain-branch -m "test: add plain branch change"
  log_cmd but push demo/plain-branch
  log_cmd create_pr "$full_repo" demo/plain-branch main "test: plain GitButler branch flow" "Live GitButler plain branch flow."
  verify_pr_base "$full_repo" demo/plain-branch main
  log_cmd gh pr view demo/plain-branch --repo "$full_repo" --json number,url,state,mergeable,headRefName,baseRefName
}

flow_multi_commit() {
  local full_repo dir count
  make_repo "multi-commit"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "multi-commit GitButler branch"

  log_cmd but branch new demo/multi-commit
  write_file session.txt "session edit one"
  log_cmd but commit demo/multi-commit -m "test: add first session edit"
  printf 'session edit two\n' >> session.txt
  printf '\n$ printf ... >> session.txt\n'
  log_cmd but commit demo/multi-commit -m "test: add second session edit"
  log_cmd but push demo/multi-commit
  count="$(git rev-list --count origin/main..demo/multi-commit)"
  [ "$count" -ge 2 ] || die "expected at least two commits in multi-commit flow"
  log_cmd create_pr "$full_repo" demo/multi-commit main "test: multi-commit GitButler branch flow" "Live GitButler multi-commit branch flow."
  verify_pr_base "$full_repo" demo/multi-commit main
  log_cmd gh pr view demo/multi-commit --repo "$full_repo" --json number,url,state,mergeable,headRefName,baseRefName,commits
}

flow_gitbutler_stack() {
  local full_repo dir
  make_repo "gitbutler-stack"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "GitButler stack"

  log_cmd but branch new demo/stack-base
  write_file stack.txt "stack base"
  log_cmd but commit demo/stack-base -m "test: add stack base"
  log_cmd but branch new --anchor demo/stack-base demo/stack-child
  printf 'stack child\n' >> stack.txt
  printf '\n$ printf ... >> stack.txt\n'
  log_cmd but commit demo/stack-child -m "test: add stack child"
  log_cmd but status
  log_cmd but push demo/stack-base
  log_cmd but push demo/stack-child
  log_cmd create_pr "$full_repo" demo/stack-base main "test: GitButler stack base flow" "Live GitButler stack base flow."
  log_cmd create_pr "$full_repo" demo/stack-child demo/stack-base "test: GitButler stack child flow" "Live GitButler stack child flow."
  verify_pr_base "$full_repo" demo/stack-base main
  verify_pr_base "$full_repo" demo/stack-child demo/stack-base
  log_cmd gh pr list --repo "$full_repo" --state open --json number,url,title,headRefName,baseRefName
  verify_pr_count "$full_repo" 2
}

flow_physical_worktrees() {
  local full_repo dir worktree_a worktree_b
  make_repo "physical-worktrees"
  full_repo="$made_full_repo"
  dir="$made_dir"
  cd "$dir"
  init_main "physical worktrees"

  worktree_a="$lab_root/physical-worktree-a"
  worktree_b="$lab_root/physical-worktree-b"
  created_dirs+=("$worktree_a" "$worktree_b")

  log_cmd but teardown || true
  log_cmd git checkout main
  log_cmd env GEST_VCS_EXECUTION=git-worktrees git worktree add -b demo/worktree-a "$worktree_a" main
  log_cmd env GEST_VCS_EXECUTION=git-worktrees git worktree add -b demo/worktree-b "$worktree_b" main

  (
    cd "$worktree_a"
    write_file workspace-a.txt "workspace a isolated change"
    log_cmd git add workspace-a.txt
    log_cmd git commit -m "test: add worktree a change"
    log_cmd git push -u origin demo/worktree-a
    log_cmd gh pr create --repo "$full_repo" --base main --head demo/worktree-a --title "test: worktree a flow" --body "Live physical worktree A flow."
    verify_pr_base "$full_repo" demo/worktree-a main
  )

  (
    cd "$worktree_b"
    write_file workspace-b.txt "workspace b isolated change"
    log_cmd git add workspace-b.txt
    log_cmd git commit -m "test: add worktree b change"
    log_cmd git push -u origin demo/worktree-b
    log_cmd gh pr create --repo "$full_repo" --base main --head demo/worktree-b --title "test: worktree b flow" --body "Live physical worktree B flow."
    verify_pr_base "$full_repo" demo/worktree-b main
  )

  log_cmd gh pr list --repo "$full_repo" --state open --json number,url,title,headRefName,baseRefName
  verify_pr_count "$full_repo" 2
  log_cmd git worktree remove "$worktree_a"
  log_cmd git worktree remove "$worktree_b"
}

run_flow "plain-branch" "Flow 1: Plain GitButler Branch PR" flow_plain_branch
run_flow "multi-commit" "Flow 2: Multi-Commit GitButler Branch PR" flow_multi_commit
run_flow "gitbutler-stack" "Flow 3: GitButler Stacked PRs" flow_gitbutler_stack
run_flow "physical-worktrees" "Flow 4: Parallel Physical Git Worktrees" flow_physical_worktrees

echo "live GitHub GitButler workflow lab passed"
echo "tutorial trace: $tutorial"
echo "logs: $logs_dir"
